export const dbTables = {
  tenants: "tenants",
  permission_profiles: "permission_profiles",
  users: "users",
  products: "products",
  product_barcodes: "product_barcodes",
  customers: "customers",
  suppliers: "suppliers",
  payment_methods: "payment_methods",
  bank_accounts: "bank_accounts",
  origin_banks: "origin_banks",
  installment_plans: "installment_plans",
  price_lists: "price_lists",
  price_list_items: "price_list_items",
  promotions: "promotions",
  purchases: "purchases",
  purchase_items: "purchase_items",
  current_account_movements: "current_account_movements",
  sales: "sales",
  sale_items: "sale_items",
  receipts: "receipts",
  invoices: "invoices",
  credit_notes: "credit_notes",
  audit_logs: "audit_logs",
  tenant_settings: "tenant_settings",
  stock_movements: "stock_movements",
  cash_sessions: "cash_sessions",
  cash_movements: "cash_movements",

  // Preparado para evolucion futura de ventas/pagos.
  sale_payments: "sale_payments",
} as const;

export type DbTableName = (typeof dbTables)[keyof typeof dbTables];

export const tenantScopedTables = [
  dbTables.users,
  dbTables.permission_profiles,
  dbTables.products,
  dbTables.product_barcodes,
  dbTables.customers,
  dbTables.suppliers,
  dbTables.payment_methods,
  dbTables.bank_accounts,
  dbTables.origin_banks,
  dbTables.installment_plans,
  dbTables.price_lists,
  dbTables.price_list_items,
  dbTables.promotions,
  dbTables.purchases,
  dbTables.purchase_items,
  dbTables.current_account_movements,
  dbTables.sales,
  dbTables.sale_items,
  dbTables.receipts,
  dbTables.invoices,
  dbTables.credit_notes,
  dbTables.tenant_settings,
  dbTables.stock_movements,
  dbTables.cash_sessions,
  dbTables.cash_movements,
  dbTables.sale_payments,
] as const;

export type TenantScopedTableName = (typeof tenantScopedTables)[number];

export const tableDefinitions: Record<DbTableName, readonly string[]> = {
  tenants: ["id", "legal_name", "trade_name", "cuit", "is_active", "created_at", "updated_at"],
  permission_profiles: ["id", "tenant_id", "name", "description", "is_active", "permissions", "created_at", "updated_at"],
  users: ["id", "tenant_id", "email", "username", "full_name", "role_code", "permission_profile_id", "is_active", "created_at", "updated_at"],
  products: ["id", "tenant_id", "code", "name", "image_url", "brand", "supplier", "description", "price", "cost_price", "stock_current", "stock_min", "stock_max", "category", "subcategory", "sale_mode", "currency_code", "price_without_vat", "vat_percent", "profit_percent", "is_favorite", "is_active", "created_at", "updated_at"],
  product_barcodes: ["id", "tenant_id", "product_id", "barcode", "is_primary", "created_at", "updated_at"],
  customers: ["id", "tenant_id", "code", "full_name", "document_type", "document_number", "fiscal_business_name", "fiscal_address", "fiscal_condition", "price_list_id", "email", "phone", "address", "observations", "current_balance", "is_active", "created_at", "updated_at"],
  suppliers: ["id", "tenant_id", "code", "name", "phone", "email", "address", "observations", "is_active", "created_at", "updated_at"],
  payment_methods: ["id", "tenant_id", "name", "code", "type", "is_active", "affects_cash", "surcharge_percent", "discount_percent", "notes", "created_at", "updated_at"],
  bank_accounts: ["id", "tenant_id", "bank_name", "account_type", "holder_name", "cbu", "alias", "currency_code", "notes", "is_active", "created_at", "updated_at"],
  origin_banks: ["id", "tenant_id", "code", "name", "is_active", "created_at", "updated_at"],
  installment_plans: ["id", "tenant_id", "code", "name", "installments", "interest_percent", "card_brand", "notes", "is_active", "created_at", "updated_at"],
  price_lists: ["id", "tenant_id", "name", "code", "description", "is_active", "price_mode", "percentage_adjustment", "created_at", "updated_at"],
  price_list_items: ["id", "tenant_id", "price_list_id", "product_id", "fixed_price", "created_at", "updated_at"],
  promotions: ["id", "tenant_id", "name", "code", "description", "type", "scope", "product_id", "min_quantity", "discount_percent", "discount_amount", "combo_price", "starts_at", "ends_at", "is_active", "created_at", "updated_at"],
  purchases: ["id", "tenant_id", "supplier_id", "purchase_number", "status", "subtotal", "total", "notes", "created_by", "created_at", "updated_at"],
  purchase_items: ["id", "tenant_id", "purchase_id", "product_id", "product_name_snapshot", "quantity", "unit_cost", "line_total", "created_at", "updated_at"],
  current_account_movements: ["id", "tenant_id", "customer_id", "sale_id", "type", "amount", "balance_after", "notes", "created_by", "created_at", "updated_at"],
  sales: ["id", "tenant_id", "sale_number", "customer_id", "cash_session_id", "status", "subtotal", "discount_total", "tax_total", "total", "currency_code", "notes", "current_account_id", "arca_document_id", "mercado_pago_preference_id", "created_at", "updated_at"],
  sale_items: ["id", "tenant_id", "sale_id", "product_id", "product_name_snapshot", "quantity", "unit_price", "discount_total", "tax_total", "line_total", "metadata", "created_at", "updated_at"],
  receipts: ["id", "tenant_id", "sale_id", "sale_number", "receipt_number", "issued_at", "customer_name", "payment_method", "items", "total", "notes", "created_by", "created_at", "updated_at"],
  invoices: ["id", "tenant_id", "sale_id", "customer_id", "document_type", "document_number", "issue_date", "customer_snapshot", "items_snapshot", "subtotal", "tax_total", "total", "status", "arca_status", "arca_reference", "arca_message", "notes", "created_at", "updated_at"],
  credit_notes: ["id", "tenant_id", "invoice_id", "sale_id", "customer_id", "document_number", "issue_date", "reason", "subtotal", "tax_total", "total", "status", "arca_status", "arca_reference", "notes", "created_at", "updated_at"],
  audit_logs: ["id", "tenant_id", "user_id", "module", "action", "entity_type", "entity_id", "description", "metadata", "created_at"],
  tenant_settings: ["id", "tenant_id", "negocio", "pos", "stock", "caja", "facturacion", "codigos_balanza", "apariencia", "sistema", "created_at", "updated_at"],
  stock_movements: ["id", "tenant_id", "product_id", "movement_type", "quantity", "reference_type", "reference_id", "notes", "created_by", "created_at", "updated_at"],
  cash_sessions: ["id", "tenant_id", "branch_id", "opened_by_user_id", "closed_by_user_id", "status", "opened_at", "closed_at", "opening_amount", "closing_amount", "expected_closing_amount", "closing_difference", "notes", "created_at", "updated_at"],
  cash_movements: ["id", "tenant_id", "cash_session_id", "movement_type", "amount", "currency_code", "reference_type", "reference_id", "notes", "created_by", "created_at", "updated_at"],
  sale_payments: ["id", "tenant_id", "sale_id", "payment_method_code", "provider", "provider_code", "amount", "currency_code", "status", "provider_status", "provider_reference", "provider_metadata", "external_reference", "metadata", "created_at", "updated_at"],
};
