export const appModules = [
  "dashboard",
  "pos",
  "productos",
  "clientes",
  "cuentas_corrientes",
  "stock",
  "caja",
  "compras",
  "proveedores",
  "listas_precios",
  "promociones",
  "medios_pago",
  "facturacion",
  "comprobantes",
  "reportes",
  "auditoria",
  "configuracion",
  "configuracion_agenda",
  "configuracion_catalogo",
  "configuracion_analisis",
  "configuracion_sistema",
  "configuracion_contable",
  "usuarios",
] as const;

export type AppModule = (typeof appModules)[number];

export const appModuleLabels: Record<AppModule, string> = {
  dashboard: "Estadisticas",
  pos: "POS",
  productos: "Productos",
  clientes: "Clientes",
  cuentas_corrientes: "Cuentas corrientes",
  stock: "Stock",
  caja: "Caja",
  compras: "Compras",
  proveedores: "Proveedores",
  listas_precios: "Listas de precios",
  promociones: "Promociones",
  medios_pago: "Medios de pago",
  facturacion: "Facturacion",
  comprobantes: "Comprobantes",
  reportes: "Reportes",
  auditoria: "Auditoria",
  configuracion: "Configuracion",
  configuracion_agenda: "Config. Agenda",
  configuracion_catalogo: "Config. Catalogo",
  configuracion_analisis: "Config. Analisis",
  configuracion_sistema: "Config. Sistema",
  configuracion_contable: "Config. Contable",
  usuarios: "Usuarios",
};
