export const routePaths = {
  login: "/login",
  home: "/",
  dashboard: "/dashboard",
  pos: "/pos",
  productos: "/productos",
  clientes: "/clientes",
  cuentasCorrientes: "/cuentas-corrientes",
  stock: "/stock",
  caja: "/caja",
  compras: "/compras",
  proveedores: "/proveedores",
  listasPrecios: "/listas-precios",
  promociones: "/promociones",
  mediosPago: "/medios-pago",
  facturacion: "/facturacion",
  comprobantes: "/comprobantes",
  reportes: "/reportes",
  auditoria: "/auditoria",
  configuracion: "/configuracion",
  usuarios: "/usuarios",
  unauthorized: "/unauthorized",
} as const;
